### ISSUE TITLE
Give option to disable WavefrontSdkMetricsRegistry

### ISSUE THREAD

**Issue by sf-lemeryfertitta** [wavefrontHQ/wavefront-sdk-python#51]
In the 1.3 update, some of our workflows have been broken by the inclusion of the forced core metric sending. Could this feature be guarded by a flag? Even if it was enabled by default, the ability to disable would be very useful for cases where we are testing or want fine-grained control over what metrics are sent and at what time they are sent.

**Comment by haosong** [comment]
PR: https://github.com/wavefrontHQ/wavefront-sdk-python/pull/57
