### ISSUE TITLE
HeartBeat service fails with shard None

### ISSUE THREAD

**Issue by AgDude** [wavefrontHQ/wavefront-sdk-python#52]
Our application_tags do not include a shard. Somehow `heartbeat.metric_tags_list` is initialized from the application tags with the shard value as `None`, event though later when the application tags are inspected the value is the string `'none'`. 

I have not investigated why this is occuring.  This error is an example of why the very broad exception handling in the `_report` method is a problem. We could have saved significant time tracking this down if there were a more helpful error message logged on those exceptions.

**Comment by haosong** [comment]
https://github.com/wavefrontHQ/wavefront-sdk-python/blob/master/wavefront_sdk/common/application_tags.py#L70
https://github.com/wavefrontHQ/wavefront-sdk-python/blob/master/wavefront_sdk/common/heartbeater_service.py#L47
We set `shard` and `cluster` to `none` by default if values are not set.

**Comment by AgDude** [comment]
Sorry, this was indeed incorrect. and it is set to the string. I found the error.
Thanks for clarifying @haosong
