### ISSUE TITLE
Add support for sending Wavefront events

### ISSUE THREAD

**Issue by vikramraman** [wavefrontHQ/wavefront-sdk-python#58]

**Comment by ustinov** [comment]
Hey @vikramraman, we do have event API client here https://github.com/wavefrontHQ/python-client/blob/master/wavefront_api_client/api/event_api.py#L238, shouldn't that one be used instead?

**Comment by vikramraman** [comment]
@ustinov The proxy now supports events as well. The ask is to enhance the SDK to support sending events to the proxy as well as direct ingestion. Here is the corresponding go implementation:

https://github.com/wavefrontHQ/wavefront-sdk-go/commit/ebcdd2502a2d3ce316b36ca3d40415115045f2b5

**Comment by haosong** [comment]
PR: https://github.com/wavefrontHQ/wavefront-sdk-python/pull/66

**Comment by xshipeng** [comment]
PR: https://github.com/wavefrontHQ/wavefront-sdk-python/pull/73
