### ISSUE TITLE
Sanitization parity with Java SDKs

### ISSUE THREAD

**Issue by sushantdewan123** [wavefrontHQ/wavefront-sdk-python#64]

**Comment by sushantdewan123** [comment]
https://github.com/wavefrontHQ/wavefront-sdk-java/commit/fd04182fcf5d7cd3aee234597e6bd1bcc9ac1ff6

**Comment by sushantdewan123** [comment]
also this https://github.com/wavefrontHQ/wavefront-sdk-java/commit/1d7dd10da3741f4754172005aec4765149c0b9ca

**Comment by vikramraman** [comment]
Note that within Java source values of the form `host:port` are currently converted to `host-port` as part of the sanitization process. It'd be preferable to retain the colon in source values as they are valid characters.

https://github.com/wavefrontHQ/wavefront-sdk-java/issues/148 for reference.
