### ISSUE TITLE
Deprecate WavefrontProxyClient

### ISSUE THREAD

**Issue by haosong** [wavefrontHQ/wavefront-sdk-python#65]
see https://github.com/wavefrontHQ/wavefront-sdk-java/issues/124

**Comment by sfc-gh-mkeller** [comment]
I believe that removing `WavefrontProxyClient` from https://github.com/wavefrontHQ/wavefront-sdk-python/blob/4528a1a9ca969b3f9e90ff6fd3d408253daf292f/wavefront_sdk/__init__.py#L14 was a breaking change and so the current version should be `2.0.0` and not `1.9.0`.

**Comment by ustinov** [comment]
Thank you for your suggestion @sfc-gh-mkeller 
I'm gonna release `2.0.0` and delete the `1.9.0` release with the breaking change
