### ISSUE TITLE
'WavefrontDirectClient' object has no attribute '_points_report_errors'

### ISSUE THREAD

**Issue by michi88** [wavefrontHQ/wavefront-sdk-python#84]
We're seeing this exception without further context but it is unclear to me how this is possible looking at the code. Only maybe when the client is closed before init finishes or can `_points_report_errors` be unset somehow? In the trace it does look like the attribute is available (`<wavefront_sdk.common.metrics.deltacounter.WavefrontSdkDeltaCounter object at 0x3e10c64b9150>`).

```
AttributeError: 'WavefrontDirectClient' object has no attribute '_points_report_errors'
  File "threading.py", line 1177, in run
    self.function(*self.args, **self.kwargs)
  File "wavefront_sdk/direct.py", line 333, in _flush
    self.flush_now()
  File "wavefront_sdk/direct.py", line 343, in flush_now
    self._points_report_errors, self._points_dropped)
```

![image](https://user-images.githubusercontent.com/1010260/136470754-c6945153-fc83-4872-b2de-76248d491f39.png)

![image](https://user-images.githubusercontent.com/1010260/136470820-71cedbe7-02db-4477-8267-522658ef6933.png)

**Comment by michi88** [comment]
Thanks for the fix! I guess we need to also fix this in the other clients right? As the direct client seems to be deprecated anyway. Although, the django integration still recommends them in the docs: https://github.com/wavefrontHQ/wavefront-django-sdk-python/issues/13. What is the recommended setup now and what changed exactly? Asking because I can't get the Django metrics to report (only manual created spans).

**Comment by xiaochenw-vmware** [comment]
> Thanks for the fix! I guess we need to also fix this in the other clients right?

You're welcome! We looked at the other two clients and they do not report internal SDK metrics in the same way as `WavefrontDirectClient`, so they shouldn't exhibit the behavior you saw.

> What is the recommended setup now and what changed exactly in the client that they're deprecated? Asking because I can't get the Django metrics to report (only manual created spans).

We'll work on this issue in https://github.com/wavefrontHQ/wavefront-django-sdk-python/issues/13

**Comment by michi88** [comment]
@xiaochenw-vmware Can you please release a new version so we can use this?
