### ISSUE TITLE
Fix Travis CI failures for pylint

### ISSUE THREAD

**Issue by oppegard** [wavefrontHQ/wavefront-sdk-python#86]
All Travis CI Checks on PRs are failing due to `pylint` errors. We need to fix this. Part of the problem is that some of the pylint errors require Python 3 to fix, but it appears we haven't officially stopped supporting Python 2.x. Another option is using pylint `disable` directives.

Failure examples:
- https://github.com/wavefrontHQ/wavefront-sdk-python/pull/83/checks
- https://github.com/wavefrontHQ/wavefront-sdk-python/pull/85/checks

Last PR with a successful ✅ `pylint` run: https://github.com/wavefrontHQ/wavefront-sdk-python/pull/82/checks

**Comment by ustinov** [comment]
We have moved from Travis CI to GitHub Actions and also have dropped Python 2.x support

Please reopen if you see any other `pylint` issues
